config/routes.rb
Rails.application.routes.draw do
  resources :accommodations
  get 'home/index'

  devise_for :users
  resources :accommodation_types
  resources :aplicacions

 

  root 'accommodations#index'

end

app/models/accommodation.rb
class Accommodation < ActiveRecord::Base
belongs_to :Accommodation_type
end

app/models/accommodation_type.rb
class AccommodationType < ActiveRecord::Base
	has_many :Accommodations
validates :descripcion, presence:true, uniqueness:true
end

app/models/aplicacion.rb
class Aplicacion < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accommodation_types_controller.rb
class AccommodationTypesController < ApplicationController
  before_action :set_accommodation_type, only: [:show, :edit, :update, :destroy]

  # GET /accommodation_types
  # GET /accommodation_types.json
  def index
    @accommodation_types = AccommodationType.all
  end

  # GET /accommodation_types/1
  # GET /accommodation_types/1.json
  def show
    @h = AccommodationType.find(params.require(:id))
  
      redirect_to :back
    
        end
  

  # GET /accommodation_types/new
  def new
    @accommodation_type = AccommodationType.new
  end

  # GET /accommodation_types/1/edit
  def edit
  end

  # POST /accommodation_types
  # POST /accommodation_types.json
  def create
    @accommodation_type = AccommodationType.new(accommodation_type_params)

    respond_to do |format|
      if @accommodation_type.save
        format.html { redirect_to @accommodation_type, notice: 'Se ha creado un nuevo tipo de hospedaje' }
        format.json { render :show, status: :created, location: @accommodation_type }
      else
        format.html { render :new }
        format.json { render json: @accommodation_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accommodation_types/1
  # PATCH/PUT /accommodation_types/1.json
  def update
    respond_to do |format|
      if @accommodation_type.update(accommodation_type_params)
        format.html { redirect_to @accommodation_type, notice: ' Se ha modificado correctamente' }
        format.json { render :show, status: :ok, location: @accommodation_type }
      else
        format.html { render :edit }
        format.json { render json: @accommodation_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accommodation_types/1
  # DELETE /accommodation_types/1.json
  def destroy
    @accommodation_type.destroy
    respond_to do |format|
      format.html { redirect_to accommodation_types_url, notice: 'Se ha eliminado un tipo de hospedaje' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accommodation_type
      @accommodation_type = AccommodationType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accommodation_type_params
      params.require(:accommodation_type).permit(:descripcion,:estado)
    end
end

app/controllers/accommodations_controller.rb
class AccommodationsController < ApplicationController
  before_action :set_accommodation, only: [:show, :edit, :update, :destroy]

  # GET /accommodations
  # GET /accommodations.json
  def index
    @accommodations = Accommodation.all
  end

  # GET /accommodations/1
  # GET /accommodations/1.json
  def show
  end

  # GET /accommodations/new
  def new
    @accommodation = Accommodation.new
  end

  # GET /accommodations/1/edit
  def edit
  end

  # POST /accommodations
  # POST /accommodations.json
  def create
    @accommodation = Accommodation.new(accommodation_params)

    respond_to do |format|
      if @accommodation.save
        format.html { redirect_to @accommodation, notice: 'Accommodation was successfully created.' }
        format.json { render :show, status: :created, location: @accommodation }
      else
        format.html { render :new }
        format.json { render json: @accommodation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accommodations/1
  # PATCH/PUT /accommodations/1.json
  def update
    respond_to do |format|
      if @accommodation.update(accommodation_params)
        format.html { redirect_to @accommodation, notice: 'Se ha creado un nuevo hospedaje.' }
        format.json { render :show, status: :ok, location: @accommodation }
      else
        format.html { render :edit }
        format.json { render json: @accommodation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accommodations/1
  # DELETE /accommodations/1.json
  def destroy
    @accommodation.destroy
    respond_to do |format|
      format.html { redirect_to accommodations_url, notice: 'Se ha eliminado el hospedaje.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accommodation
      @accommodation = Accommodation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accommodation_params
      params.require(:accommodation).permit(:titulo, :lugar, :informacion, :descripcion, :foto ,:accommodation_type_id) 
    end
end

app/controllers/aplicacions_controller.rb
class AplicacionsController < ApplicationController
  before_action :set_aplicacion, only: [:show, :edit, :update, :destroy]

  # GET /aplicacions
  # GET /aplicacions.json
  def index
    @aplicacions = Aplicacion.all
  end

  # GET /aplicacions/1
  # GET /aplicacions/1.json
  def show
  end

  # GET /aplicacions/new
  def new
    @aplicacion = Aplicacion.new
  end

  # GET /aplicacions/1/edit
  def edit
  end

  # POST /aplicacions
  # POST /aplicacions.json
  def create
    @aplicacion = Aplicacion.new(aplicacion_params)

    respond_to do |format|
      if @aplicacion.save
        format.html { redirect_to @aplicacion, notice: 'Aplicacion was successfully created.' }
        format.json { render :show, status: :created, location: @aplicacion }
      else
        format.html { render :new }
        format.json { render json: @aplicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aplicacions/1
  # PATCH/PUT /aplicacions/1.json
  def update
    respond_to do |format|
      if @aplicacion.update(aplicacion_params)
        format.html { redirect_to @aplicacion, notice: 'Accommodation type was successfully updated.' }
        format.json { render :show, status: :ok, location: @aplicacion }
      else
        format.html { render :edit }
        format.json { render json: @aplicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aplicacions/1
  # DELETE /aplicacions/1.json
  def destroy
    @aplicacion.destroy 
    respond_to do |format|
      
      format.html { redirect_to aplicacions_url, notice: 'Accommodation type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aplicacion
      @aplicacion = Aplicacion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aplicacion_params
      params.require(:aplicacion).permit(:couchinn, :descripcion)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 
  #before_action :authenticate_user!
  protect_from_forgery with: :exception


end

app/helpers/accommodation_types_helper.rb
module AccommodationTypesHelper
end

app/helpers/accommodations_helper.rb
module AccommodationsHelper
end

app/helpers/aplicacions_helper.rb
module AplicacionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/accommodation_types/_form.html.erb
<%= form_for(@accommodation_type) do |f| %>
  <% if @accommodation_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@accommodation_type.errors.count, "error") %> prohibited this accommodation_type from being saved:</h2>

      <ul>
      <% @accommodation_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accommodation_types/edit.html.erb
<h1><u>Editar tipos de hospedajes</h1> </u>

<%= render 'form' %>


<%= link_to 'Volver', accommodation_types_path, class: "btn btn-warning" %>

app/views/accommodation_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1><U>Listando tipos de hospedaje</h1></U>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Estado</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @accommodation_types.each do |accommodation_type| %>
      <tr>
        <td><%= accommodation_type.descripcion %></td>
        <td><%= accommodation_type.estado == nil ? "Vacio" : (accommodation_type.estado == true ? 'Activo' : 'Inactivo') %></td>
        <td><%= link_to 'Editar ', edit_accommodation_type_path(accommodation_type), :method => :get, :class => "btn btn-warning" %></td> 
       <td><%= link_to 'Eliminar', accommodation_type, class: "btn btn-warning" , method: :delete, data: { confirm: 'Estas seguro que desea eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Agregar nuevo tipo de hospedaje', new_accommodation_type_path %>

app/views/accommodation_types/new.html.erb
<h1><u>Agregar un nuevo hospedaje</u></h1>

<%= render 'form' %>

<%= link_to 'Volver', accommodation_types_path, class: "btn btn-warning" %>

app/views/accommodation_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @accommodation_type.Titulo %>
</p>

<p>
<strong>Descripcion:</strong>
<%= @accommodation.Descripcion %>
</p>

<p>
<strong>Tipo de hospedaje:</strong>
<% if @accommodation.accommodation_type_id.nil? %>
<%= @accommodation.accommodation_type_id %>
<% else %>
<%= accommodationType.find(@accommodation.accommodation_type_id).Descripcion %>
<% <%end%>
</p>
	
	<p>
	<strong>Imagen:</strong>
<%= @accommodation.Imagen %>
</p>
<p>
<strong>Email del propietario:</strong>
<%= @accommodation.user.Email %>
</p>





<%= link_to 'volver', accommodation_types_path, class: "btn btn-warning" %> 

app/views/accommodations/_form.html.erb
<%= form_for(@accommodation) do |f| %>
  <% if @accommodation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@accommodation.errors.count, "error") %> prohibited this accommodation from being saved:</h2>

      <ul>
      <% @accommodation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :lugar %><br>
    <%= f.text_field :lugar %>
  </div>
  <div class="field">
    <%= f.label :informacion %><br>
    <%= f.text_field :informacion %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :foto %><br>
    <%= f.text_field :foto %>
  </div>

<div class="field">
    <%= f.label "tipo de hospedaje" %><br>
    <%= f.select :accommodation_type_id,     options_for_select(AccommodationType.all.map { |a| [a.descripcion, a.id]}, f.object.accommodation_type_id), class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>



<% end %>

app/views/accommodations/edit.html.erb
<h1>Editando Hospedaje</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @accommodation %> |
<%= link_to 'Volver', accommodations_path %>

app/views/accommodations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listando Hospedajes</h1>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Lugar</th>
      <th>Informacion</th>
      <th>Descripcion</th>
      <th>Tipo de hospedaje</th>
      <th>Foto</th>


      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accommodations.each do |accommodation| %>
      <tr>
        <td><%= accommodation.titulo %></td>
        <td><%= accommodation.lugar %></td>
        <td><%= accommodation.informacion %></td>
        <td><%= accommodation.descripcion %></td>
        <td><%= AccommodationType.find(accommodation.accommodation_type_id).descripcion %></td>
        <td><%= image_tag(:Foto) %></td> 


        <td><%= link_to 'Mostrar', accommodation, :method => :get, :class => "btn btn-warning"  %></td>
        <td><%= link_to 'Editar', edit_accommodation_path(accommodation), :method => :get, :class => "btn btn-warning" %></td> 
        </td>
        <td><%= link_to 'Eliminar', accommodation,:class => "btn btn-danger", method: :delete, data: { confirm: 'esta seguro que desea eliminar ' + accommodation.titulo + '?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo hospedaje', new_accommodation_path %>

app/views/accommodations/new.html.erb
<h1>Nuevo hospedaje</h1>

<%= render 'form' %>

<%= link_to 'Volver', accommodations_path %>

app/views/accommodations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @accommodation.titulo %>
</p>

<p>
  <strong>Lugar:</strong>
  <%= @accommodation.lugar %>
</p>

<p>
  <strong>Informacion:</strong>
  <%= @accommodation.informacion %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @accommodation.descripcion %>
</p>

<p>
  <strong>Foto:</strong>
  <%= image_tag(:Foto) %>
</p>
<p>
  <strong>Tipo de hospedaje:</strong>
  <%= AccommodationType.find(@accommodation.accommodation_type_id).descripcion %>
</p>


<%= link_to 'Editar', edit_accommodation_path(@accommodation) %> |
<%= link_to 'Volver', accommodations_path %>

app/views/aplicacions/_form.html.erb
<%= form_for(@aplicacion) do |f| %>
  <% if @aplicacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aplicacion.errors.count, "error") %> prohibited this aplicacion from being saved:</h2>

      <ul>
      <% @aplicacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :couchinn %><br>
    <%= f.text_field :couchinn %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aplicacions/edit.html.erb
<h1>Editing Aplicacion</h1>

<%= render 'form' %>

<%= link_to 'Show', @aplicacion %> |
<%= link_to 'Back', aplicacions_path %>

app/views/aplicacions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Aplicacions</h1>

<table>
  <thead>
    <tr>
      <th>Couchinn</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aplicacions.each do |aplicacion| %>
      <tr>
        <td><%= aplicacion.couchinn %></td>
        <td><%= aplicacion.descripcion %></td>
        <td><%= link_to 'Mostrar', aplicacion %></td>
        <td><%= link_to 'Editar', edit_aplicacion_path(aplicacion) %></td>
        <td><%= link_to 'Eliminar', aplicacion, method: :delete, data: { confirm: 'Esta seguro que desea eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aplicacion', new_aplicacion_path %>

app/views/aplicacions/new.html.erb
<h1>New Aplicacion</h1>

<%= render 'form' %>

<%= link_to 'Back', aplicacions_path %>

app/views/aplicacions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Couchinn:</strong>
  <%= @aplicacion.couchinn %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @aplicacion.descripcion %>
</p>

<%= link_to 'Editar', edit_aplicacion_path(@aplicacion) %> |
<%= link_to 'Volver', aplicacions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proyecto Couch-IN</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<h1 style="text-align:center;">COUCH-IN</html></h1>
<p   style="text-align:center;">Alquila con confianza.</p> 
<body> </body>


<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Editar perfil', edit_user_registration_path , :class => 'navbar-link' %> |
  <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Registrarse", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Iniciar sesion", new_user_session_path, :class => 'navbar-link'  %>



<% end %>

<%= yield %>




</html>